### ISSUE TITLE
[FE] 선택 옵션

### ISSUE THREAD

**Issue by hwangJN** [softeerbootcamp-2nd/A4-FourEver#13]
## 📝 Description

내차만들기 / 선택 옵션 페이지 구현

## 🌟 Tasks
- [x] 선택옵션 페이지 레이아웃 구성
+ /feat13-optionSelectPage

- [x] 옵션카드 hove시 딤처리와 옵션 요약 나타나기
+ /feat13-optionSelelctHover

- [x] 옵션카드 버튼 상태 추가하기/취소하기 로 변경 & 상태에 따른 버튼 bgColor 변경
+ /feat13-optionSelectButton

- [x] 옵션 삭제시 상태 변경하기
+ /feat13-optionRemove

- [x] 선택옵션 -> H Genuine Accessories -> N Performance 별로 다른 옵션 구성
+ /feat13-optionPageChange

- [x] 기본 옵션 클릭시 modal
+ /feat13-optionModal

- [x] 옵션 위치 보기 카드 뒤집기
+ /feat13-optionLocationView

- [x] 옵션 위치 보기 넘버링
+ /feat13-optionLocationNumbering
