### ISSUE TITLE
[refactor] 코드 리팩토링

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#139]
## 📝 Description

코드 리팩토링

## 🌟 Tasks

- [x] svg 파일 컴포넌트화
- [x] 코드 재사용 줄이기
- [x]  매직넘버 및 문구 상수화
+ /refactor
