### ISSUE TITLE
[FE] 내 차 만들기 완성

### ISSUE THREAD

**Issue by hwangJN** [softeerbootcamp-2nd/A4-FourEver#14]
## 📝 Description

내 차 만들기 / 내 차 만들기 완성

## 🌟 Tasks

- [x] 완성 차 페이지 라우터 만들기
+ /feat14-completePage
- [x] 완성 차 소개 top 배너
+ /completeTopBanner
- [x] 완성 차 기능 배너
+ /completeFunctionBanner
- [x] 완성 차 옵션 배너
+ /selectedOption
- [x] 추가 절차 버튼
+ /addProcessBtn

- [x]  툴팁 나타나지 않기
- /feat14-fixToolTip

- [x]  푸터 버튼(이 차량 구매하기) 빼고 내용 전부 지우기
- /feat14-completePageFooter

## 🌟 Refactor
- [x] 받아오는 데이터 구조 변경
+ /feat14-refactorData

**Comment by meanz1** [comment]
내 차 만들기 완성페이지 구현 완성 !
