### ISSUE TITLE
[WE] CI/CD

### ISSUE THREAD

**Issue by ShinHeeEul** [softeerbootcamp-2nd/A4-FourEver#141]
## 📝 Description

구현할 기능 작성

## 🌟 Tasks

- [x] 테스트 빌드환경 조성
- [x] Dockerfile 설정
- [x] CI/CD 적용
- [x] DB 의존성 제거
