### ISSUE TITLE
[FE] 아카이빙 메인 페이지

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#146]
## 📝 Description

아카이빙 메인 페이지

## 🌟 Tasks

- [x] 아카이빙/마이카이빙 공통 컴포넌트 헤더 만들기
+ /chivingHeader
<img width="1225" alt="스크린샷 2023-08-14 오후 4 23 24" src="https://github.com/softeerbootcamp-2nd/A4-FourEver/assets/62049151/9b258f20-3ca7-45f1-bfd0-be13ac0d10c8">

- [x] 아카이빙 메인 페이지 레이아웃 구성
+ /feat146-archivingLayout

- [x] hover 시 스타일 수정
+ /feat146-archivingHover

- [x] 옵션칩 & 필터탭 onClick 이벤트
+ /feat146-archivingClick

- [x] API 적용
+ /feat146-archivingAPI
