### ISSUE TITLE
기본 API 구현

### ISSUE THREAD

**Issue by LBC11** [softeerbootcamp-2nd/A4-FourEver#154]
## 📝 Description
아카이빙 페이지를 위한 기본 API 구현

## 🌟 Tasks

- [ ] 차량별 선택할 수 있는 선택 옵션 목록 API
- [ ] 차량별 특정 옵션을 선택한 전체 후기 API
- [ ] 차량별 특정 옵션을 선택한 시승 혹은 후기 API
- [ ] 특정 후기의 자세한 정보 API
