### ISSUE TITLE
[BE] EC2 설정

### ISSUE THREAD

**Issue by LBC11** [softeerbootcamp-2nd/A4-FourEver#22]
## 📝 Description
WebApp-Produciton-Server: 주 웹 애플리케이션 호스팅을 위한 서버

## 🌟 Tasks

- [x] 인스턴스 유형 선택
- [x] AMI 선택
- [x] 보안 그룹 설정
- [x] 키 페어 생성 및 설정
- [x] 스토리지 설정
- [x] 인스턴스 시작
- [x] Elastic IP 할당
- [x] jdk-11 설치
- [x] 도커 설치
- [x] 백엔드 도커 이미지 파일 배포
- [x] 프론트엔드 도커 이미지 파일 배포
