### ISSUE TITLE
[BE] MySQL 설정

### ISSUE THREAD

**Issue by LBC11** [softeerbootcamp-2nd/A4-FourEver#23]
## 📝 Description
EC2의 WebApp에서 사용할 데이터베이스 관리 시스템 설정

## 🌟 Tasks

- [x] MySQL 설치
- [x] MySQL 구성
- [x] MySQL 서버 시작
- [x] MySQL 보안 설정
- [x] 데이터베이스 및 사용자 생성
- [x] 스키마 생성
- [x] 더미 데이터 입력
- [x] 백업 및 복구 전략 설정
