### ISSUE TITLE
[FE] 마이카이빙 리팩토링

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#247]
## 📝 Description

마이카이빙 디자인 리팩토링

## 🌟 Tasks

- [ ] 내가 만든 차량 목록 width 맞추기
- [ ] 스크롤 커스텀
- [ ] 내가 만든 차량 목록 카드 데이터 없을 때(엔진, 구동방식 등등)
+ /mychivingDesign

- [ ] 피드에서 저장한 차량 목록 카드 x버튼 추가 및 삭제 API 연결
+ /deleteArchivingCard

- [ ] 내가 만든 차량 목록 및 피드에서 저장한 차량 목록 없을 경우
+ /emptyCard
