### ISSUE TITLE
[FE] 마이카이빙 페이지(카드 재생성)

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#265]
## 📝 Description

마이카이빙 페이지 내 내가 만든 차량 목록 및 아카이빙에서 저장한 차량 목록 카드 변경.(원래 기획 디자인대로)

## 🌟 Tasks

- [x] 내가 만든 차량 목록 카드 생성
- [x] 아카이빙에서 저장한 차량 목록 카드 워딩 변경 및 선택 옵션 추가
- [x] 탭 만들기 (내가 만든 차량 목록 / 아카이빙에서 저장한 차량 목록)
+ /mychivingRemake
