### ISSUE TITLE
[BE] VPC 적용하기

### ISSUE THREAD

**Issue by ShinHeeEul** [softeerbootcamp-2nd/A4-FourEver#276]
## 📝 Description
- VPC를 활용하여 데이터베이스 인스턴스와 백/프론트엔드 인스턴스를 분리하고 안전하게 보관하기

## 🌟 Tasks

- [x] VPC 생성

- [x] public, private 서브넷 생성

- [x] 라우팅 테이블 생성 후 각 규칙에 맞는 서브넷과 연결

- [x] 인터넷 게이트웨이 생성

- [x] 데이터베이스 인스턴스를 private 서브넷에서 생성

- [x] 백과 프론트엔드 인스턴스를 AMI로 이미지화 시킨 후 public 서브넷으로 생성
