### ISSUE TITLE
[BE] 기본 API 구현

### ISSUE THREAD

**Issue by LBC11** [softeerbootcamp-2nd/A4-FourEver#30]
## 📝 Description

기본 API 구현

## 🌟 Tasks

- [x] 차량 정보 api
- [x]  차량 트림 정보 api
- [x] 차량 기본 옵션 api
- [x] 차량 선택 옵션 api
- [x] 차량 시승/구매 리뷰 api
- [x] 내 차 만들기 결과 api
- [x] 내 차 만들기의 각 페이지에서 필요한 데이터 한번에 조회하게 수정
- [x] JDBC template으로 전환
