### ISSUE TITLE
[FE] 내차만들기 - 옵션 패치

### ISSUE THREAD

**Issue by hwangJN** [softeerbootcamp-2nd/A4-FourEver#81]
## 📝 Description

내 차 만들기 옵션 데이터를 실제 서버로 GET 요청 보내서 받는다.

## 🌟 Tasks

- [x] Api.js 셋팅(내차만들기 api 3개 - 1.트림 옵션 2. 색상 옵션 3. 선택옵션)
+ /feat81-setApi
- [x] 트림 옵션 데이터 load -> 적용
+ /feat81-trimData
- [x] 색상 옵션 데이터 load -> 적용
+ /feat81-colorData
- [x] 선택 옵션 데이터 load -> 적용
+ /feat81-selectData
