### ISSUE TITLE
[FE] 완성페이지 리팩토링

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#86]
## 📝 Description

내차만들기 내 완성페이지 리팩토링

## 🌟 Tasks

- [x] 완성된 차량~ 글씨 크기 조정 및 '마이카이빙 바로가기' 버튼 생성
+ /ToMychivingBtn

- [x] 완성페이지 로딩시 등장 애니메이션에서 스크롤 막기
+ /feat86-scrollForbid

- [x] 선택옵션 이미지 뜨게 하기
+ /feat86-selectedImg

- [x] 선택한 펠리세이드 이미지로 완성
+ /feat86-selectedCarImg
