### ISSUE TITLE
[FE] 최상단 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#92]
## 📝 Description

최상단 컴포넌트 리팩토링 한다(Header, Alert)

## 🌟 Tasks

- [x] Alert창 디자인
+ /styleAlert
- [x] 좌측 현대 로고 클릭 시 나오는 창 문구와 오른쪽 아카이빙 클릭 시 나오는 창 문구 차이를 둔다
+ /differentMsgAlert
- [x] Alert창 내 우측 버튼 누를 시 해당하는 페이지로 이동한다
+ /forMovingAlert
- [x] 아카이빙, 마이카이빙, 내차만들기 에 따른 헤더 상태 관리 
+ /headerState
